<a href="https://colab.research.google.com/github/piaoruilin/STAT343/blob/main/DataAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
import pandas as pd

Mounted at /content/drive

In [3]:
pip install statsmodels pandas

Requirement already satisfied: statsmodels in /usr/local/lib/python3.10/dist-packages (0.14.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: numpy>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.25.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (1.11.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (0.5.6)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.6->statsmodels) (1.16.0)

In [ ]:
vix=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/VIX.csv')
exchange=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/대원화환율.csv')
exchage2=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/대미달러.csv')
product=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/한국_산업생산지수(계절변동조정)_22140956.csv')
operation=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/제조업 생산능력 및 가동률 지수_22142916.csv')
ship=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/출하.csv')
inventory=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/재고.csv')
invest=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/설비투자지수_22142509.csv')
leading=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/선행종합지수.csv')
exchange3=pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/엔화달러.csv')

In [ ]:
#현빈 컬럼 이름 바꾸기
vix.columns = ['Date', 'VIX']
exchange.columns = ['Date', 'KRWUSD','KRWJPY','KRWEUR']
exchage2.columns = ['Date', 'EURUSD']
product.columns = ['Date', 'IPI']
operation.columns = ['Date', 'OPER_IDX','OPER_ADJ']
ship.columns = ['Date', 'SHIP_IDX','SHIP_ADJ']
inventory.columns = ['Date', 'STOCK_IDX','STOCK_ADJ']
invest.columns = ['Date', 'PLANTIV_IDX','PLANTIV_ADJ']
leading.columns = ['Date', 'ECOB_IDX']
exchange3.columns = ['Date', 'JPYUSD']

In [ ]:
PPI_KR = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/한국_생산자물가지수.csv') #보류(결측치 해결)
PPI_US = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/미국_생산자물가지수.csv')
PPI_JP = pd.read_excel('/content/drive/MyDrive/관세청 공모전/data/일본_생산자물가지수.xlsx')
COTTON = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_원면.csv')
CORN = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_옥수수.csv')
ALUMIN = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_알루미늄.csv')
ZINC = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_아연.csv')
WHEAT = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_소맥.csv')
NIKEL = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_니켈.csv')
COPPER = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/국제상품가격_구리.csv')

In [ ]:
#ECOS에서 받은 자료 피벗하고 컬럼명 바꾸기

#investing.com에서 받은 자료 컬럼명 바꾸기

PPI_US.columns = ['Date', 'PPI_US']

dataframes = [PPI_KR, PPI_JP, COTTON, ALUMIN, COPPER, WHEAT, CORN, ZINC, NIKEL ]
dataframe_names = ["PPI_KR", "PPI_JP", "COTTON", "ALUMIN", "COPPER", "WHEAT", "CORN", "ZINC", "NIKEL"]

# 각 DataFrame 처리
for i, (df, name) in enumerate(zip(dataframes, dataframe_names)):
    # 날짜와 가격 데이터를 담을 새로운 DataFrame 생성
    dates = df.columns[4:]  # 5번째 컬럼부터 끝까지가 날짜임
    prices = df.iloc[0, 4:].values  # 첫 번째 행의 5번째 컬럼부터 끝까지가 가격임

    new_df = pd.DataFrame({
        'Date': dates,
        name: prices
    })

    # 변환된 DataFrame을 원래 변수 이름으로 다시 저장
    globals()[name] = new_df

print("파일 변환이 완료되었습니다.")

파일 변환이 완료되었습니다.

In [ ]:
DAX = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_독일(Dax).csv')
DOW = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_미국(Dow Jones).csv')
NASDAQ = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_미국(NASDAQ).csv')
STI = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_싱가포르(STI).csv')
STOXX = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_유로(STOXX).csv')
NIKKEI = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_일본(NIKKEI).csv')
SHCOMP = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_중국(SHCOMP).csv')
KOSPI = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_한국(KOSPI).csv')
HANG = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/주가_홍콩(HSI).csv')

In [ ]:
EX_IM_TOT = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/수출입 실적(품목별)_20240626.csv')

In [ ]:
EX_IM_TOT = EX_IM_TOT[['기간', 'HS코드', 'Amount of Export/Import']]
EX_IM_TOT.rename(columns={'Amount of Export/Import': 'EX/IM_TOT'}, inplace=True)

In [ ]:
EX_IM_TOT= EX_IM_TOT[['기간', 'HS코드', 'Amount of Export/Import']]
EX_IM_TOT.rename(columns={'Amount of Export/Import': 'EX/IM_TOT'}, inplace=True)

KeyError: "['Amount of Export/Import'] not in index"

In [ ]:
EX_IM_TOT.head(10)

In [ ]:
HScode_27 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 27]
HScode_29 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 29]
HScode_39 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 39]
HScode_72 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 72]
HScode_84 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 84]
HScode_85 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 85]
HScode_87 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 87]
HScode_90 = EX_IM_TOT[EX_IM_TOT['HS코드'] == 90]

In [ ]:
DAX.columns = ['Date', 'DAX']
DOW.columns = ['Date', 'DOW']
NASDAQ.columns = ['Date', 'NASDAQ']
STI.columns = ['Date', 'STI']
STOXX.columns = ['Date', 'STOXX']
NIKKEI.columns = ['Date', 'NIKKEI']
SHCOMP.columns = ['Date', 'SHCOMP']
KOSPI.columns = ['Date', 'KOSPI']
HANG.columns = ['Date', 'HANG']

In [ ]:
#지윤이꺼 역순으로 바꾸기

ji=pd.concat([DAX,DOW,NASDAQ,STI,STOXX,NIKKEI,SHCOMP,KOSPI,HANG], axis=1)
ji_reversed = ji.iloc[::-1].reset_index(drop=True)

In [ ]:
ji_reversed

In [ ]:
ECO_R = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/동행종합지수.csv')
ECO_A = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/후행종합지수.csv')
ENERGY = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/에너지소비량.csv')
EMPLOY = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/경제활동인구.csv')
IIP_JP = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/산업생산지수(일본).csv')
IIP_US = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/산업생산지수(미국).csv')
CLI = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/Composite Leading Indicator(OECD).csv') #다시
SPRATE_US = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/Spread(US).csv')
EFFR_US = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/EFFR(US).csv')
IM_US = pd.read_csv('/content/drive/MyDrive/관세청 공모전/data/Amount of Imports(US).csv')

In [ ]:
EMPLOY=EMPLOY.iloc[:,[0,4]]
EMPLOY

         변환   원자료.3
0   2021/01  26,566
1   2021/02  26,990
2   2021/03  27,114
3   2021/04  27,169
4   2021/05  27,210
5   2021/06  27,280
6   2021/07  27,340
7   2021/08  27,381
8   2021/09  27,464
9   2021/10  27,506
10  2021/11  27,579
11  2021/12  27,661
12  2022/01  27,739
13  2022/02  28,043
14  2022/03  27,939
15  2022/04  28,034
16  2022/05  28,124
17  2022/06  28,107
18  2022/07  28,160
19  2022/08  28,175
20  2022/09  28,166
21  2022/10  28,178
22  2022/11  28,206
23  2022/12  28,193
24  2023/01  28,173
25  2023/02  28,358
26  2023/03  28,403
27  2023/04  28,386
28  2023/05  28,458
29  2023/06  28,434
30  2023/07  28,372
31  2023/08  28,438
32  2023/09  28,474
33  2023/10  28,519
34  2023/11  28,484
35  2023/12  28,495

In [ ]:
ECO_R.columns = ['Date', 'ECO_R']
ECO_A.columns = ['Date', 'ECO_A']
ENERGY=ENERGY.iloc[:,:2]
ENERGY.columns = ['Date', 'ENERGY']
EMPLOY.columns = ['Date', 'EMPLOY']
IIP_JP.columns = ['Date', 'IIP_JP']
IIP_US.columns = ['Date', 'IIP_US']
CLI=CLI.iloc[:,[0,15]]
CLI.columns = ['Date', 'CLI']

SPRATE_US.columns = ['Date', 'SPRATE_US']
EFFR_US.columns = ['Date', 'EFFR_US']
IM_US.columns = ['Date', 'IM_US']

In [ ]:
#다합치기

result = pd.concat([vix,exchange, exchange3,exchage2,product,operation,ship,inventory,invest,PPI_KR,PPI_US,PPI_JP,COTTON,CORN,ALUMIN,ZINC,WHEAT,NIKEL,COPPER,ECO_R,ECO_A,ENERGY,EMPLOY,IIP_JP,IIP_US,CLI,SPRATE_US,EFFR_US,IM_US,ji_reversed],axis=1)

In [ ]:
date=result.iloc[:,0]
rest=result.iloc[:,1:]

rest2=rest.drop('Date',axis=1)
rest2

data=pd.concat([date,rest2],axis=1)
df = data.dropna(axis=0)

In [ ]:
# 쉽표 없애기

df['KRWUSD'] = pd.to_numeric(df['KRWUSD'].str.replace(',', ''), errors='coerce')
df['KRWJPY'] = pd.to_numeric(df['KRWJPY'].str.replace(',', ''), errors='coerce')
df['KRWEUR'] = pd.to_numeric(df['KRWEUR'].str.replace(',', ''), errors='coerce')
df['IM_US'] = pd.to_numeric(df['IM_US'].str.replace(',', ''), errors='coerce')

<ipython-input-18-61dcb771f3f1>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['KRWUSD'] = pd.to_numeric(df['KRWUSD'].str.replace(',', ''), errors='coerce')
<ipython-input-18-61dcb771f3f1>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['KRWJPY'] = pd.to_numeric(df['KRWJPY'].str.replace(',', ''), errors='coerce')
<ipython-input-18-61dcb771f3f1>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['KRWEUR'] = pd.to_numeric(df['KRWEUR'].str.replace(',', ''), errors='coerce')
<ipython-input-18-61dcb771f3f1>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['IM_US'] = pd.to_numeric(df['IM_US'].str.replace(',', ''), errors='coerce')

In [ ]:
df['COPPER'] = pd.to_numeric(df['COPPER'].str.replace(',', ''), errors='coerce')
df['ALUMIN'] = pd.to_numeric(df['ALUMIN'].str.replace(',', ''), errors='coerce')
df['ZINC'] = pd.to_numeric(df['ZINC'].str.replace(',', ''), errors='coerce')
df['NIKEL'] = pd.to_numeric(df['NIKEL'].str.replace(',', ''), errors='coerce')

df['EMPLOY'] = pd.to_numeric(df['EMPLOY'].str.replace(',', ''), errors='coerce')
df['ENERGY'] = pd.to_numeric(df['ENERGY'].str.replace(',', ''), errors='coerce')

df

<ipython-input-19-e0a222158f91>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['COPPER'] = pd.to_numeric(df['COPPER'].str.replace(',', ''), errors='coerce')
<ipython-input-19-e0a222158f91>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ALUMIN'] = pd.to_numeric(df['ALUMIN'].str.replace(',', ''), errors='coerce')
<ipython-input-19-e0a222158f91>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ZINC'] = pd.to_numeric(df['ZINC'].str.replace(',', ''), errors='coerce')
<ipython-input-19-e0a222158f91>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['NIKEL'] = pd.to_numeric(df['NIKEL'].str.replace(',', ''), errors='coerce')
<ipython-input-19-e0a222158f91>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['EMPLOY'] = pd.to_numeric(df['EMPLOY'].str.replace(',', ''), errors='coerce')
<ipython-input-19-e0a222158f91>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ENERGY'] = pd.to_numeric(df['ENERGY'].str.replace(',', ''), errors='coerce')

,Date,VIX,KRWUSD,KRWJPY,KRWEUR,JPYUSD,EURUSD,IPI,OPER_IDX,OPER_ADJ,...,IM_US,DAX,DOW,NASDAQ,STI,STOXX,NIKKEI,SHCOMP,KOSPI,HANG
0,2021-01-01,24.910000,1097.49,1058.52,1336.31,103.68130,1.21770,112.5,100.2,102.0,...,204812211,13432.87,29982.62,45.09,2902.52,3481.44,27663.39,3483.07,2976.21,28283.71
1,2021-02-01,23.140526,1111.72,1055.14,1344.60,105.36500,1.20950,115.8,92.7,106.4,...,193811524,13786.29,30932.37,46.10,2949.04,3636.44,28966.01,3509.08,3012.95,28980.21
2,2021-03-01,21.843043,1131.02,1040.86,1346.74,108.66680,1.19080,114.0,109.3,104.4,...,237293470,15008.34,32981.55,49.15,3165.34,3919.21,29178.80,3441.91,3061.42,28378.35
3,2021-04-01,17.416190,1119.40,1025.98,1338.47,109.11000,1.19580,113.4,104.1,103.1,...,226862947,15135.91,33874.85,53.85,3218.27,3974.74,28812.63,3446.86,3147.86,28724.88
4,2021-05-01,19.760500,1123.28,1029.14,1363.91,109.14970,1.21420,112.3,102.5,102.1,...,230832117,15421.13,34529.45,55.82,3164.28,4039.46,28860.08,3615.48,3203.92,29151.80
5,2021-06-01,16.956818,1121.30,1018.50,1351.94,110.09230,1.20580,113.2,108.2,103.4,...,242889376,15531.04,34502.51,58.60,3130.46,4064.30,28791.53,3591.20,3296.68,28827.95
6,2021-07-01,17.603333,1143.98,1037.25,1352.72,110.29550,1.18250,115.1,107.1,104.7,...,237793423,15544.39,34935.47,62.24,3166.94,4089.30,27283.59,3397.36,3202.32,25961.03
7,2021-08-01,17.472727,1160.34,1056.31,1365.63,109.85000,1.17700,116.3,101.0,105.4,...,245819152,15835.09,35360.73,65.26,3055.05,4196.41,28089.54,3543.94,3199.27,25878.99
8,2021-09-01,19.824762,1169.54,1061.22,1378.19,110.20900,1.17850,115.1,102.4,104.4,...,244362935,15260.69,33843.92,64.34,3086.70,4048.08,29452.66,3568.17,3068.82,24575.64
9,2021-10-01,17.871429,1182.82,1044.91,1372.24,113.21420,1.16020,116.7,105.6,104.9,...,251085362,15688.77,35819.56,69.96,3198.17,4250.56,28892.69,3547.34,2970.68,25377.24
10,2021-11-01,18.500476,1182.91,1036.36,1350.43,114.14300,1.14170,117.6,110.3,106.2,...,259402268,15100.13,34483.72,67.74,3041.29,4063.06,27821.76,3563.89,2839.01,23475.26
11,2021-12-01,21.354545,1183.70,1039.51,1338.19,113.87260,1.13050,122.6,116.6,111.7,...,257909183,15884.86,36338.30,70.00,3123.68,4298.41,28791.71,3639.78,2977.65,23397.67
12,2022-01-01,23.181000,1194.01,1039.55,1353.20,114.86150,1.13340,122.8,106.0,111.6,...,248125007,15471.20,35131.86,59.74,3249.59,4174.60,27001.98,3361.44,2663.34,23802.26
13,2022-02-01,25.748421,1198.34,1039.85,1359.89,115.24280,1.13480,121.1,98.2,109.2,...,234429533,14461.02,33892.60,57.05,3242.24,3924.23,26526.82,3462.31,2699.18,22713.02
14,2022-03-01,26.968696,1221.03,1028.59,1345.33,118.77690,1.10180,121.9,112.7,109.5,...,296960601,14414.75,34678.35,59.40,3408.52,3902.52,27821.43,3252.20,2757.65,21996.85
15,2022-04-01,24.373500,1232.34,977.38,1334.08,126.10520,1.08270,120.0,107.9,107.4,...,273079278,14097.88,32977.21,52.46,3356.90,3802.86,26847.90,3047.06,2695.05,21089.39
16,2022-05-01,29.313636,1269.88,985.49,1342.43,128.86714,1.05720,117.9,109.2,105.4,...,285413576,14388.35,32990.12,51.75,3232.49,3789.21,27279.80,3186.43,2685.90,21415.20
17,2022-06-01,28.233182,1277.35,951.34,1348.96,134.27225,1.05618,119.8,108.9,107.3,...,286099839,12783.77,30775.43,50.85,3102.21,3454.86,26393.04,3398.62,2332.64,21859.79
18,2022-07-01,24.995238,1307.40,955.93,1332.91,136.77238,1.01955,117.5,106.2,105.7,...,271116400,13484.05,32845.13,60.30,3211.56,3708.10,27801.64,3253.24,2451.50,20156.51
19,2022-08-01,22.169565,1318.44,975.17,1334.53,135.21023,1.01234,114.2,99.8,102.9,...,283770157,12834.96,31510.43,59.53,3221.67,3517.25,28091.53,3202.14,2472.05,19954.39
20,2022-09-01,27.341818,1391.59,973.20,1377.09,142.98675,0.98977,113.3,100.0,102.2,...,275409936,12114.36,28725.51,56.68,3130.24,3318.20,25937.21,3024.39,2155.49,17222.83
21,2022-10-01,30.005714,1426.66,969.36,1404.83,147.19579,0.98469,111.0,101.6,99.4,...,282708530,13253.74,32732.95,62.24,3093.11,3617.54,27587.46,2893.48,2293.61,14687.02
22,2022-11-01,23.299091,1364.10,956.51,1388.29,142.61182,1.01829,110.8,103.2,99.2,...,256183173,14397.04,34589.77,68.46,3290.49,3964.72,27968.99,3151.34,2472.53,18597.23
23,2022-12-01,21.784286,1296.22,959.12,1371.13,135.15545,1.05784,106.7,103.3,96.7,...,253135559,13923.59,33147.25,61.35,3251.32,3793.62,26094.50,3089.26,2236.40,19781.41
24,2023-01-01,20.169048,1247.25,956.76,1342.37,130.36925,1.07639,109.2,92.3,99.8,...,254350333,15128.27,34086.04,60.19,3365.67,4163.45,27327.11,3255.67,2425.08,21842.33
25,2023-02-01,20.120500,1270.74,956.68,1361.65,132.81900,1.07175,108.3,91.4,96.9,...,230789781,15365.14,32656.70,56.06,3262.63,4238.38,27445.56,3279.61,2412.85,19785.94
26,2023-03-01,21.644348,1305.73,977.31,1398.50,133.63136,1.07109,112.1,105.8,100.9,...,262821911,15628.84,33274.15,54.67,3258.90,4315.05,28041.48,3272.86,2476.86,20400.11
27,2023-04-01,17.817895,1320.01,990.52,1446.41,133.26850,1.09573,111.0,99.0,99.9,...,250670498,15922.38,34098.16,55.37,3270.51,4359.31,28856.44,3323.27,2501.53,19894.57
28,2023-05-01,17.636087,1328.21,969.37,1444.20,137.04750,1.08731,114.9,103.2,102.9,...,264147992,15664.02,32908.27,55.35,3158.80,4218.04,30887.88,3204.56,2577.12,18234.27
29,2023-06-01,14.003182,1296.71,918.39,1405.98,141.22071,1.08431,112.6,103.9,100.9,...,258113566,16147.90,34407.60,49.85,3205.91,4399.09,33189.04,3202.06,2564.28,18916.43
30,2023-07-01,13.932381,1286.30,911.74,1421.87,141.09214,1.10553,109.6,98.9,98.4,...,255661960,16446.83,35559.53,50.49,3373.98,4471.31,33172.22,3291.04,2632.58,20078.94
31,2023-08-01,15.853913,1318.47,911.40,1439.04,144.66227,1.09151,115.6,100.2,103.1,...,266023300,15947.08,34721.16,52.48,3233.30,4297.11,32619.34,3119.88,2556.27,18382.06
32,2023-09-01,15.173333,1329.47,901.65,1422.61,147.45079,1.07008,117.8,102.3,103.6,...,261282312,15386.58,33507.76,48.59,3217.41,4174.66,31857.62,3110.48,2465.07,17809.66
33,2023-10-01,18.887727,1350.69,903.72,1427.31,149.46079,1.05672,115.8,102.0,102.2,...,276809670,14810.34,33052.74,49.60,3067.74,4061.12,30858.85,3018.77,2277.99,17112.48
34,2023-11-01,14.019091,1310.39,874.28,1415.59,149.88273,1.08043,117.6,106.5,102.6,...,255976281,16215.43,35950.96,55.84,3072.99,4382.47,33486.89,3029.67,2535.29,17042.88
35,2023-12-01,12.718500,1303.98,904.83,1422.28,144.14025,1.09078,117.1,104.5,101.3,...,247462546,16751.64,37689.54,58.14,3240.27,4521.65,33464.17,2974.93,2655.28,17047.39

In [ ]:
print(df.columns)

In [ ]:
df=df.drop(['OPER_IDX','SHIP_IDX','STOCK_IDX','PLANTIV_IDX'],axis=1)

In [ ]:
df

In [ ]:
# ADF 검정

from statsmodels.tsa.stattools import adfuller
# ADF 테스트 결과 저장할 딕셔너리
adf_results = {}

# 각 컬럼에 대해 ADF 테스트 실행
for column in df.columns:
    if column == 'Date':
        continue  # 날짜 컬럼은 제외
    result = adfuller(df[column].dropna())  # NaN 값 제거 후 ADF 테스트 실행
    adf_results[column] = result
    print(f"ADF Test Results for {column}:")
    print(f"ADF Statistic: {result[0]}")
    print(f"p-value: {result[1]}")
    print(f"Critical Values: {result[4]}")
    if result[1] > 0.05:
        print(f"Column {column} has a unit root (p-value > 0.05)")
    else:
        print(f"Column {column} does not have a unit root (p-value <= 0.05)")
    print("\n")

print("ADF 테스트가 완료되었습니다.")

In [ ]:
# ADF 테스트 결과 저장할 딕셔너리
adf_results = {}

# 각 컬럼에 대해 ADF 테스트 실행 및 차분 후 재검정
for column in df.columns:
    if column == 'Date':
        continue  # 날짜 컬럼은 제외

    # ADF 테스트 실행
    result = adfuller(df[column].dropna())  # NaN 값 제거 후 ADF 테스트 실행
    adf_results[column] = result

    # p-value가 0.05를 넘는 경우 차분
    if result[1] > 0.05:
        # 차분 수행
        df[column] = df[column].diff().dropna()

        # 차분 후 다시 ADF 테스트 실행
        result_diff = adfuller(df[column].dropna())
        adf_results[column] = result_diff

        # 차분된 결과를 원래 DataFrame의 해당 컬럼에 저장
        df[column] = df[column]

        print(f"ADF Test Results after differencing for {column}:")
        print(f"ADF Statistic: {result_diff[0]}")
        print(f"p-value: {result_diff[1]}")
        print(f"Critical Values: {result_diff[4]}")

        if result_diff[1] > 0.05:
            print(f"Column {column} still has a unit root after differencing (p-value > 0.05)")
        else:
            print(f"Column {column} does not have a unit root after differencing (p-value <= 0.05)")
    else:
        print(f"Column {column} does not have a unit root (p-value <= 0.05)")

    print("\n")

print("차분 및 재검정이 완료되었습니다.")

In [ ]:
# PP 검정 2트

import pandas as pd
import statsmodels.api as sm
from statsmodels.tsa.stattools import adfuller  # Import adfuller for PP test

# "Date" 열을 제외한 나머지 열들에 대해 PP 검정 수행
for column in df.columns:
    if column != 'Date':
        # Use adfuller with 'ct' regression for PP test
        result = sm.tsa.stattools.adfuller(df[column].dropna(), regression='ct')
        p_value = result[1]
        print(f'Column: {column}')
        print(result)
        if result[1] > 0.05:
            print(f"Column {column} has a unit root (p-value > 0.05)")
        else:
            print(f"Column {column} does not have a unit root (p-value <= 0.05)")
        print("\n")
        print('\n')

Column: VIX
(-1.735720970188708, 0.7348975942295418, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 120.3894929875735)
Column VIX has a unit root (p-value > 0.05)




Column: KRWUSD
(-2.584348383314261, 0.287149252836579, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, 241.60310502463508)
Column KRWUSD has a unit root (p-value > 0.05)




Column: KRWJPY
(-4.365793346003526, 0.002481436324294138, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, 210.50788497874063)
Column KRWJPY does not have a unit root (p-value <= 0.05)




Column: KRWEUR
(-3.5299524218343703, 0.03629338833375698, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, 215.71271441004055)
Column KRWEUR does not have a unit root (p-value <= 0.05)




Column: JPYUSD
(-2.458619148534725, 0.34895032439574375, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, 135.43637986458435)
Column JPYUSD has a unit root (p-value > 0.05)




Column: EURUSD
(-1.2818471617988954, 0.8923453313507976, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, -125.31299752485015)
Column EURUSD has a unit root (p-value > 0.05)




Column: IPI
(-3.800450678582689, 0.016537873366897625, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, 118.76066962991268)
Column IPI does not have a unit root (p-value <= 0.05)




Column: OPER_ADJ
(-4.581765156765767, 0.0011060241190853067, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, 110.81262733701783)
Column OPER_ADJ does not have a unit root (p-value <= 0.05)




Column: SHIP_ADJ
(-4.290536172552091, 0.0032545063605627293, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, 105.85725937095651)
Column SHIP_ADJ does not have a unit root (p-value <= 0.05)




Column: STOCK_ADJ
(-1.4176483562137303, 0.8556569361304174, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 128.18629645349043)
Column STOCK_ADJ has a unit root (p-value > 0.05)




Column: PLANTIV_ADJ
(-2.850544530600178, 0.17899967998803962, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 153.68220415319678)
Column PLANTIV_ADJ has a unit root (p-value > 0.05)




Column: PPI_KR
(-1.6084979427365438, 0.7890868626579652, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 109.84724822429499)
Column PPI_KR has a unit root (p-value > 0.05)




Column: PPI_US
(-1.1639619429767494, 0.9176301839603387, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, 138.65805508901073)
Column PPI_US has a unit root (p-value > 0.05)




Column: PPI_JP
(0.23751004390297187, 0.9959791666024064, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 42.8083757248263)
Column PPI_JP has a unit root (p-value > 0.05)




Column: COTTON
(-2.400460081402496, 0.37937436375185385, 3, 32, {'1%': -4.27353517944336, '5%': -3.5578989233398435, '10%': -3.2123659912109375}, 172.08031441074183)
Column COTTON has a unit root (p-value > 0.05)




Column: CORN
(-1.263501613298139, 0.8966619561336192, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 211.97792464805312)
Column CORN has a unit root (p-value > 0.05)




Column: ALUMIN
(-5.530147145397835, 2.0084907648907595e-05, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, 301.4399762756743)
Column ALUMIN does not have a unit root (p-value <= 0.05)




Column: ZINC
(-1.8415316781967694, 0.6843961496064239, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 346.8059677727941)
Column ZINC has a unit root (p-value > 0.05)




Column: WHEAT
(-1.4660101110207024, 0.8404824898116721, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, 228.74250443437737)
Column WHEAT has a unit root (p-value > 0.05)




Column: NIKEL
(-1.925577882368715, 0.6413137789719974, 1, 34, {'1%': -4.253042608385915, '5%': -3.5485904579686545, '10%': -3.2070617952371263}, 465.5337649672545)
Column NIKEL has a unit root (p-value > 0.05)




Column: COPPER
(-3.1447694465506, 0.09597923772570299, 2, 33, {'1%': -4.262944107465843, '5%': -3.553092543339733, '10%': -3.2096284957008097}, 375.99224410640466)
Column COPPER has a unit root (p-value > 0.05)




Column: ECO_R
(-0.5000033901742796, 0.983433684013045, 3, 32, {'1%': -4.27353517944336, '5%': -3.5578989233398435, '10%': -3.2123659912109375}, -14.750365020579657)
Column ECO_R has a unit root (p-value > 0.05)




Column: ECO_A
(-3.0574426552328697, 0.11672243885542316, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, -31.189608095137828)
Column ECO_A has a unit root (p-value > 0.05)




Column: ENERGY
(-3.985306005970248, 0.009225747425654142, 9, 26, {'1%': -4.356652259899864, '5%': -3.595299990896677, '10%': -3.233575694128357}, 436.20657466217557)
Column ENERGY does not have a unit root (p-value <= 0.05)




Column: EMPLOY
(-3.507218297948667, 0.0386248309019501, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 284.26059421612604)
Column EMPLOY does not have a unit root (p-value <= 0.05)




Column: IIP_JP
(-2.9076120851618255, 0.15976654154264436, 10, 25, {'1%': -4.3749647199999995, '5%': -3.6034675359999997, '10%': -3.23818632}, 79.94997416684078)
Column IIP_JP has a unit root (p-value > 0.05)




Column: IIP_US
(-2.4460442822786765, 0.3554414660306324, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 40.61030872921249)
Column IIP_US has a unit root (p-value > 0.05)




Column: CLI
(-1.7988723916722917, 0.7053017905157156, 4, 31, {'1%': -4.284890375281125, '5%': -3.5630415894061964, '10%': -3.2152919724077744}, -158.9344634186693)
Column CLI has a unit root (p-value > 0.05)




Column: SPRATE_US
(-3.3166744462827147, 0.06355685549906448, 3, 32, {'1%': -4.27353517944336, '5%': -3.5578989233398435, '10%': -3.2123659912109375}, -156.1092679196265)
Column SPRATE_US has a unit root (p-value > 0.05)




Column: EFFR_US
(-3.079213352158748, 0.11126232684144488, 5, 30, {'1%': -4.2970953703703705, '5%': -3.5685571851851847, '10%': -3.2184266666666668}, -28.33552407326175)
Column EFFR_US has a unit root (p-value > 0.05)




Column: IM_US
(-3.2511155544953825, 0.07468896088428979, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 903.0817939416127)
Column IM_US has a unit root (p-value > 0.05)




Column: DAX
(-1.8051668373705028, 0.7022616048199167, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 402.9735948192556)
Column DAX has a unit root (p-value > 0.05)




Column: DOW
(-2.9493846094385803, 0.1467859802359437, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 442.59484553575396)
Column DOW has a unit root (p-value > 0.05)




Column: NASDAQ
(-4.177986695334432, 0.004831959893895555, 5, 30, {'1%': -4.2970953703703705, '5%': -3.5685571851851847, '10%': -3.2184266666666668}, 140.5368816403979)
Column NASDAQ does not have a unit root (p-value <= 0.05)




Column: STI
(-3.974699256637928, 0.009549396087250432, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 298.34139734701154)
Column STI does not have a unit root (p-value <= 0.05)




Column: STOXX
(-2.093841585700722, 0.5495436120659596, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 337.52144335557733)
Column STOXX has a unit root (p-value > 0.05)




Column: NIKKEI
(-1.6327224114460777, 0.7793578700058287, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 428.5033317053133)
Column NIKKEI has a unit root (p-value > 0.05)




Column: SHCOMP
(-3.138713249184406, 0.0973197336259985, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 315.24380762336546)
Column SHCOMP has a unit root (p-value > 0.05)




Column: KOSPI
(-0.8589748432342348, 0.9603413973559072, 2, 33, {'1%': -4.262944107465843, '5%': -3.553092543339733, '10%': -3.2096284957008097}, 323.30471313680454)
Column KOSPI has a unit root (p-value > 0.05)




Column: HANG
(-2.3692201719722803, 0.3961051121286499, 0, 35, {'1%': -4.243765510204081, '5%': -3.5443646122448977, '10%': -3.2046503498542274}, 434.60245856533334)
Column HANG has a unit root (p-value > 0.05)